/**
 * Shared in-memory schema for the payment tests. Mirrors src/db/schema.ts for
 * the tables the money rails touch, so every test file boots the same database.
 */
import { getDb } from "../../src/db/client";

export async function createTestSchema(): Promise<void> {
  const db = getDb();
  const client = (db as unknown as { $client: { exec: (sql: string) => Promise<unknown> } }).$client;
  await client.exec(`
  CREATE TABLE IF NOT EXISTS events (id text PRIMARY KEY, slug text NOT NULL, name text NOT NULL, name_bengali text, theme text NOT NULL DEFAULT 'none', description text, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, venue_name text, venue_address text, venue_map_url text, poster_url text, days jsonb, status text NOT NULL DEFAULT 'draft', publish_at timestamptz, is_member_only boolean NOT NULL DEFAULT false, created_by text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS ticket_types (id text PRIMARY KEY, event_id text NOT NULL, name text NOT NULL, description text, pricing_model text NOT NULL DEFAULT 'per_person', price_member_cents integer NOT NULL, price_nonmember_cents integer NOT NULL, age_band text NOT NULL DEFAULT 'all', day_keys jsonb, with_food boolean NOT NULL DEFAULT true, check_in_start text, capacity integer, sold_count integer NOT NULL DEFAULT 0, requires_food_selection boolean NOT NULL DEFAULT true, sale_starts_at timestamptz, sale_ends_at timestamptz, display_order integer NOT NULL DEFAULT 0, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS promo_codes (id text PRIMARY KEY, event_id text, code text NOT NULL, discount_type text NOT NULL, discount_value integer NOT NULL, max_uses_total integer, max_uses_per_member integer DEFAULT 1, current_uses integer NOT NULL DEFAULT 0, valid_from timestamptz, valid_until timestamptz, created_by text, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS registrations (id text PRIMARY KEY, confirmation_number text NOT NULL, event_id text NOT NULL, member_id text, buyer_email text NOT NULL, buyer_name text NOT NULL, buyer_phone text, is_member_purchase boolean NOT NULL DEFAULT false, source text NOT NULL DEFAULT 'web', subtotal_cents integer NOT NULL, discount_cents integer NOT NULL DEFAULT 0, total_cents integer NOT NULL, processing_fee_cents integer NOT NULL DEFAULT 0, donation_cents integer NOT NULL DEFAULT 0, membership_signup boolean NOT NULL DEFAULT false, self_declared_member boolean NOT NULL DEFAULT false, promo_code_id text, payment_method text NOT NULL, status text NOT NULL DEFAULT 'pending_payment', square_order_id text, square_payment_id text, zelle_verified_by text, zelle_verified_at timestamptz, zelle_sent_clicked_at timestamptz, paid_at timestamptz, cancelled_at timestamptz, reservation_expires_at timestamptz, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS tickets (id text PRIMARY KEY, registration_id text NOT NULL, ticket_type_id text NOT NULL, attendee_first_name text NOT NULL, attendee_last_name text, attendee_age integer, attendee_is_member boolean NOT NULL DEFAULT false, food_pref text, dietary_notes text, student_info jsonb, day_key text DEFAULT 'all', price_cents integer NOT NULL DEFAULT 0, qr_code text NOT NULL, checked_in_at timestamptz, checked_in_by text, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS donations (id text PRIMARY KEY, confirmation_number text NOT NULL, member_id text, donor_name text NOT NULL, donor_email text NOT NULL, donor_phone text, amount_cents integer NOT NULL, in_honor_or_memory text NOT NULL DEFAULT 'none', designation text, honoree_name text, honoree_notify_email text, message text, is_anonymous boolean NOT NULL DEFAULT false, payment_method text NOT NULL, status text NOT NULL DEFAULT 'pending_payment', square_order_id text, square_payment_id text, zelle_verified_by text, zelle_verified_at timestamptz, paid_at timestamptz, cancelled_at timestamptz, reservation_expires_at timestamptz, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, email text NOT NULL, password_hash text NOT NULL, email_verified_at timestamptz, role text NOT NULL DEFAULT 'member', last_login_at timestamptz, failed_login_count integer NOT NULL DEFAULT 0, last_failed_login_at timestamptz, locked_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
  CREATE TABLE IF NOT EXISTS members (id text PRIMARY KEY, user_id text NOT NULL, family_name text NOT NULL, primary_first_name text NOT NULL, primary_last_name text NOT NULL, phone text, address_line1 text, address_line2 text, city text, state text, zip text, country text DEFAULT 'US', membership_status text NOT NULL DEFAULT 'pending_payment', membership_started_at date, square_order_id text, membership_expires_at timestamptz, member_number text, source text NOT NULL DEFAULT 'account', notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
  CREATE TABLE IF NOT EXISTS family_members (id text PRIMARY KEY, member_id text NOT NULL, first_name text NOT NULL, last_name text, relationship text NOT NULL DEFAULT 'spouse', date_of_birth date, food_pref text NOT NULL DEFAULT 'non_veg', dietary_notes text, is_member boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS audit_log (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, user_id text, action text NOT NULL, entity_type text NOT NULL, entity_id text, changes jsonb, ip_address text, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS system_config (key text PRIMARY KEY, value jsonb, updated_at timestamptz NOT NULL DEFAULT now(), updated_by text);
  CREATE TABLE IF NOT EXISTS counters (key text PRIMARY KEY, value integer NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS email_log (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, to_email text NOT NULL, original_to_email text, template text NOT NULL, subject text NOT NULL, body_text text, status text NOT NULL DEFAULT 'queued', provider_message_id text, error text, related_user_id text, related_registration_id text, sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS email_outbox (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, to_email text NOT NULL, subject text NOT NULL, body_text text, body_html text, template text NOT NULL, priority integer NOT NULL DEFAULT 2, digest_key text, related_user_id text, related_registration_id text, attempts integer NOT NULL DEFAULT 0, next_attempt_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'queued', last_error text, created_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS password_reset_tokens (id text PRIMARY KEY DEFAULT gen_random_uuid()::text, user_id text NOT NULL, token_hash text NOT NULL, purpose text NOT NULL DEFAULT 'reset', expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
  
  CREATE TABLE IF NOT EXISTS processed_webhook_events (event_id text PRIMARY KEY, provider text NOT NULL DEFAULT 'square', processed_at timestamptz NOT NULL DEFAULT now());
  `);
  const { ensurePaymentsTable } = await import("../../src/lib/ledger-ensure");
  await ensurePaymentsTable();
  // Everything the app adds lazily at boot, applied the same way here.
  const { ensurePaymentIntegritySchema } = await import("../../src/lib/payments/ensure");
  await ensurePaymentIntegritySchema();
}
