/**
 * Wipe test data before going live (or to reset a dev database).
 *
 * Default ("transactional wipe") — removes everything generated by testing,
 * KEEPS everything you configured by hand:
 *   ✗ deletes: registrations, tickets, meal scans, donations, email log,
 *     webhook dedupe records, contact messages, password-reset tokens,
 *     audit log, confirmation-number counters, member-role accounts
 *     (demo families) + their family members
 *   ✓ keeps: admin/volunteer accounts, events, ticket types (sold counts
 *     reset to 0), promo codes (use counts reset), scan window setup,
 *     settings, photos, magazines, sponsors, team
 *
 * --all — scorched earth: also deletes events, ticket types, promo codes,
 *     scan windows, magazines metadata, media metadata, sponsors, team,
 *     and ALL user accounts. Settings (system_config) are kept so you don't
 *     lose org emails; delete rows manually if you want pure factory state.
 *
 * Usage (server stopped if using local PGlite — it's single-connection):
 *   npx tsx scripts/reset-test-data.ts --yes            # transactional wipe
 *   npx tsx scripts/reset-test-data.ts --yes --all      # full wipe
 *   DATABASE_URL=postgres://… npx tsx scripts/reset-test-data.ts --yes
 */
import { eq, inArray, sql } from "drizzle-orm";
import { getDb, schema } from "../src/db/client";

const args = process.argv.slice(2);
const confirmed = args.includes("--yes");
const wipeAll = args.includes("--all");

async function main() {
  if (!confirmed) {
    console.log("Refusing to run without --yes.");
    console.log("  npx tsx scripts/reset-test-data.ts --yes         # wipe test registrations/donations/demo members");
    console.log("  npx tsx scripts/reset-test-data.ts --yes --all   # ALSO wipe events, users, media, everything");
    process.exit(1);
  }
  const db = getDb();
  const target = process.env.DATABASE_URL ? "remote Postgres (DATABASE_URL)" : `local PGlite (${process.env.PGLITE_DIR ?? "./.data/pglite"})`;
  console.log(`Resetting ${wipeAll ? "EVERYTHING" : "transactional test data"} on ${target}…\n`);

  const del = async (label: string, fn: () => Promise<unknown>) => {
    try {
      await fn();
      console.log(`  ✗ cleared ${label}`);
    } catch (e) {
      // table may not exist yet on a fresh DB — that's fine
      console.log(`  – skipped ${label} (${e instanceof Error ? e.message.split("\n")[0] : e})`);
    }
  };

  // ── transactional data (always) ──────────────────────────────
  await del("ticket_scans", () => db.delete(schema.ticketScans));
  await del("tickets", () => db.delete(schema.tickets));
  await del("registrations", () => db.delete(schema.registrations));
  await del("donations", () => db.delete(schema.donations));
  await del("email_log", () => db.delete(schema.emailLog));
  await del("processed_webhook_events", () => db.delete(schema.processedWebhookEvents));
  await del("contact_messages", () => db.delete(schema.contactMessages));
  await del("password_reset_tokens", () => db.delete(schema.passwordResetTokens));
  await del("audit_log", () => db.delete(schema.auditLog));
  await del("counters (PRG-/DON- numbering restarts)", () => db.delete(schema.counters));

  if (!wipeAll) {
    // demo member accounts (role=member) + their families; admins/volunteers stay
    const memberUsers = await db.select().from(schema.users).where(eq(schema.users.role, "member"));
    if (memberUsers.length > 0) {
      const userIds = memberUsers.map((u) => u.id);
      const memberRows = await db.select().from(schema.members).where(inArray(schema.members.userId, userIds));
      const memberIds = memberRows.map((m) => m.id);
      if (memberIds.length > 0) {
        await del("family_members (of member accounts)", () =>
          db.delete(schema.familyMembers).where(inArray(schema.familyMembers.memberId, memberIds))
        );
      }
      await del("members (member accounts)", () => db.delete(schema.members).where(inArray(schema.members.userId, userIds)));
      await del(`users (${memberUsers.length} member-role accounts)`, () =>
        db.delete(schema.users).where(inArray(schema.users.id, userIds))
      );
    }
    // reset counts on kept rows
    await del("ticket_types.sold_count → 0", () => db.update(schema.ticketTypes).set({ soldCount: 0 }));
    await del("promo_codes.current_uses → 0", () => db.update(schema.promoCodes).set({ currentUses: 0 }));
    await del("scan window scans (windows kept, re-closed)", () =>
      db.update(schema.scanSessions).set({ status: "closed", openedAt: null, closedAt: null })
    );
  } else {
    // ── scorched earth ──────────────────────────────────────────
    await del("scan_sessions", () => db.delete(schema.scanSessions));
    await del("promo_codes", () => db.delete(schema.promoCodes));
    await del("ticket_types", () => db.delete(schema.ticketTypes));
    await del("events", () => db.delete(schema.events));
    await del("family_members", () => db.delete(schema.familyMembers));
    await del("members", () => db.delete(schema.members));
    await del("users (ALL — including admins)", () => db.delete(schema.users));
    await del("magazines (metadata — delete files in Blob/public manually)", () => db.delete(schema.magazines));
    await del("media_images (metadata — delete files in Blob/public manually)", () => db.delete(schema.mediaImages));
    await del("sponsors", () => db.delete(schema.sponsors));
    await del("team_members", () => db.delete(schema.teamMembers));
  }

  // sanity report
  const [{ n: regs }] = await db.select({ n: sql<number>`count(*)` }).from(schema.registrations);
  const [{ n: users }] = await db.select({ n: sql<number>`count(*)` }).from(schema.users);
  console.log(`\nDone. registrations=${regs}, users=${users}.`);
  if (!wipeAll) console.log("Kept: admin/volunteer accounts, events, settings, photos, magazines.");
  else console.log("Full wipe complete — run `npm run seed` (dev) or create a super admin before using the app.");
}

main().then(() => process.exit(0)).catch((e) => {
  console.error(e);
  process.exit(1);
});
